spring:
  resources:
    cache-period: 0
  jmx:
    enabled: false
broker:
  enabled: ${BROKER_ENABLED:false}
  host: ${BROKER_HOST:127.0.0.1}
  port: ${BROKER_PORT:61613}
  login: ${BROKER_LOGIN:guest}
  password: ${BROKER_PASSWORD:guest}
  virtual-host: ${BROKER_VIRTUAL_HOST:}
---
spring:
  profiles: default
client:
  path: '../opensnap-client/web/'
  # Use directly build directory, need to run pub build before, useful for using the JS version
  #path: '../opensnap-client/build/web'
broker:
  enabled: false
---
spring:
  profiles: local
broker:
  enabled: false
---
spring:
  profiles: cloud
broker:
  enabled: false




