app:
  usr:
    signup: 'ANONYMOUS'
  '*': 'USER'
user:
  queue:
    'error': 'ANONYMOUS,USER'
    'user-created': 'ANONYMOUS'
    '*': 'USER'
queue:
  'snap-created': 'ADMIN'
topic:
  'user-authenticated': 'USER'
  'snap-created': 'USER'
  'user-created': 'USER'
