name: opensnap
version: 0.2.0
dependencies:
  angular: 0.9.10
  browser: any
  js: any
  unittest: any
  angular_ui: '>=0.2.2 <0.3.0'
  stomp: 0.7.2
  collection: any
  logging: any
  route_hierarchical: '>=0.4.17 <0.5.0'
 
