name: opensnap
version: 0.4.0
dependencies:
  angular: 0.12.0
  browser: any
  js: any
  angular_ui: 0.5.5
  stomp: 0.7.2
  stomp_sockjs: 0.0.1
  collection: any
  logging: any
dev_dependencies:
  unittest: any
transformers:
- angular
 
