name: opensnap
version: 0.4.0
dependencies:
  angular: '>=1.0.0 <2.0.0'
  browser: any
  js: any
  angular_ui:
    git: 'https://github.com/akserg/angular.dart.ui.git'
  stomp: 0.7.2
  stomp_sockjs: 0.0.1
  collection: any
  logging: any
dev_dependencies:
  unittest: any
transformers:
- angular
 
