name: opensnap
version: 0.4.0
dependencies:
  angular: 0.10.0
  browser: any
  js: any
  angular_ui:
    git: https://github.com/akserg/angular.dart.ui.git
  stomp: 0.7.2
  collection: any
  logging: any
  route_hierarchical: '>=0.4.17 <0.5.0'
  inject: any
dev_dependencies:
  unittest: any
transformers:
- angular
 
