name: opensnap
version: 0.2.0
dependencies:
  angular: 0.9.10
  browser: any
  js: any
  unittest: any
  angular_ui:
    git: https://github.com/akserg/angular.dart.ui.git
  stomp: 0.7.2
  collection: any
  logging: any
 
